 - name: ".NET update"
   color: "a870c9"
   description: "Update to .net global.json"

 - name: "auto-pr"
   color: "0000aa"
   description: "Pull request created automatically"

 - name: "buildbot"
   color: "96f7d2"
   description: "Changes in BuildBot project"

 - name: "buildbot-cloudformation"
   color: "96f7d2"
   description: "Changes in BuildBot.CloudFormation project"

 - name: "buildbot-cloudformation-tests"
   color: "0e8a16"
   description: "Changes in BuildBot.CloudFormation.Tests project"

 - name: "buildbot-discord"
   color: "96f7d2"
   description: "Changes in BuildBot.Discord project"

 - name: "buildbot-github"
   color: "96f7d2"
   description: "Changes in BuildBot.GitHub project"

 - name: "buildbot-health"
   color: "96f7d2"
   description: "Changes in BuildBot.Health project"

 - name: "buildbot-json"
   color: "96f7d2"
   description: "Changes in BuildBot.Json project"

 - name: "buildbot-servicemodel"
   color: "96f7d2"
   description: "Changes in BuildBot.ServiceModel project"

 - name: "buildbot-tests"
   color: "0e8a16"
   description: "Changes in BuildBot.Tests project"

 - name: "buildbot-watchtower"
   color: "96f7d2"
   description: "Changes in BuildBot.Watchtower project"

 - name: "C#"
   color: "db6baa"
   description: "C# Source Files"

 - name: "C# Project"
   color: "db6baa"
   description: "C# Project Files"

 - name: "C# Solution"
   color: "db6baa"
   description: "C# Solutions"

 - name: "Change Log"
   color: "53fcd4"
   description: "Changelog tracking file"

 - name: "Config Change"
   color: "d8bb50"
   description: "Configuration files changes"

 - name: "dependencies"
   color: "0366d6"
   description: "Updates to dependencies"

 - name: "DO NOT MERGE"
   color: "ff0000"
   description: "This pull request should not be merged yet"

 - name: "dotnet"
   color: "db6baa"
   description: "Dotnet package updates"

 - name: "github-actions"
   color: "e09cf4"
   description: "Github actions workflow files"

 - name: "Markdown"
   color: "5319e7"
   description: "Markdown files"

 - name: "Migration Script"
   color: "b680e5"
   description: "SQL Migration scripts"

 - name: "no-pr-activity"
   color: "ffff00"
   description: "Pull Request has had no activity for a long time"

 - name: "npm"
   color: "e99695"
   description: "npm package update"

 - name: "Powershell"
   color: "23bc12"
   description: "Powershell Source Files"

 - name: "Read Me"
   color: "5319e7"
   description: "Repository readme file"

 - name: "Setup"
   color: "5319e7"
   description: "Setup instructions"

 - name: "Solidity"
   color: "413cd1"
   description: "Solidity Source Files"

 - name: "SQL"
   color: "413cd1"
   description: "SQL Source Files"

 - name: "Static Code Analysis Rules"
   color: "00dead"
   description: "Ruleset for static code analysis files"

 - name: "Tech Debt"
   color: "30027a"
   description: "Technical debt"

 - name: "Unit Tests"
   color: "0e8a16"
   description: "Unit test and integration test projects"

