<?xml version="1.0" encoding="utf-8"?>

<Project>
    <!-- Common company metadata -->
    <PropertyGroup>
        <Authors>FunFair</Authors>
        <Company>FunFair</Company>
        <Copyright>FunFair</Copyright>
        <Product>FunFair</Product>
    </PropertyGroup>

    <!-- Release notes; if any - injected in at build time -->
    <PropertyGroup>
        <PackageReleaseNotes>$(ReleaseNotes)</PackageReleaseNotes>
    </PropertyGroup>

    <!-- Repository type -->
    <PropertyGroup>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    </PropertyGroup>

    <!-- Only add these properties in if the project is publishable or packable.
         TODO: Find a better piece of metadata that gets defined _only_ during publish or pack
    -->
    <PropertyGroup>
        <FFPacking>False</FFPacking>
        <FFPacking Condition="$(IsPackable) == 'true' OR $(IsPublishable) == 'true'">True</FFPacking>
    </PropertyGroup>

    <!-- Package Icon -->
    <PropertyGroup>
        <_PackageIconFile>$([System.IO.Path]::Combine('$(MSBuildThisFileDirectory)', 'packageicon.png'))</_PackageIconFile>
    </PropertyGroup>
    <PropertyGroup Condition="$(FFPacking) == 'True' AND Exists('$(_PackageIconFile)')">
        <PackageIcon>packageicon.png</PackageIcon>
        <PackageIconUrl>https://avatars.githubusercontent.com/u/29401895</PackageIconUrl>
    </PropertyGroup>
    <ItemGroup Condition="$(FFPacking) == 'True' AND Exists('$(_PackageIconFile)')">
        <None Include="$(_PackageIconFile)" Pack="true" PackagePath="\" />
    </ItemGroup>

    <!-- License -->
    <PropertyGroup>
        <_LicenseFile>$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..', 'LICENSE'))</_LicenseFile>
    </PropertyGroup>
    <PropertyGroup Condition="$(FFPacking) == 'True' AND Exists('$(_LicenseFile)')">
        <PackageLicense>LICENSE</PackageLicense>
        <PackageLicenseUrl>$(RepositoryUrl)/blob/main/LICENSE.md</PackageLicenseUrl>
    </PropertyGroup>
    <ItemGroup Condition="$(FFPacking) == 'True' AND Exists('$(_LicenseFile)')">
        <None Include="$(_LicenseFile)" Pack="true" PackagePath="\" />
    </ItemGroup>

    <!-- Readme -->
    <PropertyGroup>
        <_ReadmeFile>$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..', 'README.md'))</_ReadmeFile>
    </PropertyGroup>
    <PropertyGroup Condition="$(FFPacking) == 'True' AND Exists('$(_ReadmeFile)')">
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup Condition="$(FFPacking) == 'True' AND Exists('$(_ReadmeFile)')">
        <None Include="$(_ReadmeFile)" Pack="true" PackagePath="\" />
    </ItemGroup>

    <!-- Disable Nuget errors on publishing -->
    <PropertyGroup Condition="$(FFPublishing) == 'True'">
        <WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
    </PropertyGroup>

    <!-- Enable SBOM generation in production builds -->
    <PropertyGroup Condition="$(FFPacking) == 'True' AND $(IsProduction) == 'True'">
        <EnableSbom>true</EnableSbom>
    </PropertyGroup>

    <!-- Sarif -->
    <PropertyGroup Condition="$(EnableSarif)=='True' And !$(MSBuildProjectName.EndsWith('.Tests'))">
        <_SarifLogFile>$([MSBuild]::NormalizePath('$(SolutionDir)', '..', 'results', '$(MSBuildProjectName).$(TargetFramework).sarif'))</_SarifLogFile>
        <ErrorLog>$(_SarifLogFile),version=2.1</ErrorLog>
        <ReportAnalyzer>true</ReportAnalyzer>
    </PropertyGroup>
</Project>
