--- # Build and deploy packages
# Maintain in repo: funfair-server-template
name: 'Publish to nuget using multi-push (With integrated symbol feed)'
description: 'Publishes Nuget packages with multi-push (With integrated symbol feed)'
inputs:
  nuget-feed:
    description: 'Nuget feed to push packages to'
    required: false
  nuget-api-key:
    description: 'API key to authenticate when pushing packages'
    required: false

runs:
  using: "composite"
  steps:

    - name: "NuGet Push with Symbols"
      uses: ./.github/actions/dotnet-tool-run
      with:
        working-directory: "${{github.workspace}}"
        tool-name: "pushpackages"
        tool-arguments: "--folder dist --api-key \"${{inputs.nuget-api-key}}\" --source \"${{inputs.nuget-feed}}\""
